# controller_frequency: 5.0
oscillation_timeout: 30.0
oscillation_distance: 0.5
planner_patience: 1.0
controller_patience: 1.0 

TrajectoryPlannerROS:
  max_vel_x: 0.15
  min_vel_x: 0.05
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  min_in_place_vel_theta: 0.25

  sim_time: 2.0
  vx_samples: 5

  acc_lim_theta: 2.5
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  path_distance_bias: 2
  goal_distance_bias: 1

  holonomic_robot: false
  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25

  recovery_behavior_enabled: false
  clearing_rotation_allowed: false

DWAPlannerROS:
  max_vel_x: 0.55  
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.2 
  min_vel_trans: 0.05  
  trans_stopped_vel: 0.01

  max_vel_theta: 0.5 
  min_vel_theta: 0 
  theta_stopped_vel: 0.01

  acc_lim_x: 2.5 
  acc_lim_theta: 2.5
  acc_lim_y: 0

  yaw_goal_tolerance: 0.25 
  xy_goal_tolerance: 0.15 

  sim_time: 2.0     
  vx_samples: 5  

  path_distance_bias: 64.0