local_costmap:
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  global_frame: odom
  resolution: 0.01
  rolling_window: true
  inflation_layer:
    inflation_radius: 1.0
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}